config/routes.rb
# frozen_string_literal: true

::Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  ::ActiveAdmin.routes(self)

  get 'schedule' => 'schedule#show', as: 'show_schedule'
  get 'history' => 'history#month', as: 'show_history'
  get 'history/small' => 'history#three_days', as: 'show_history_small'
  get 'today' => 'today#show', as: 'show_today'
  get 'my_account' => 'account#show', as: 'my_account'
  get 'stats' => 'stats#show', as: 'show_stats'

  namespace :api do
    devise_scope :user do
      post '/sessions' => 'sessions#create', as: 'create_session'
      delete '/sessions' => 'sessions#destroy', as: 'destroy_session'
    end

    get '/users' => 'users#show', as: 'show_user'
    put '/users' => 'users#update', as: 'update_user'

    post '/tasks' => 'tasks#create', as: 'create_task'
    put '/tasks' => 'tasks#update', as: 'update_task'
    delete '/tasks/:task_id' => 'tasks#destroy', as: 'destroy_task'

    get '/today(/:date)' => 'today#show', as: 'show_today'

    get '/schedule' => 'schedule#show', as: 'show_schedule'

    get '/history' => 'history#month', as: 'show_history'
    get '/history/three_days' => 'history#three_days', as: 'show_history_three_days'

    get '/stats' => 'stats#show', as: 'show_stats'
    get '/stats/chartkick' => 'stats#chartkick', as: 'stats_chartkick'

    post '/daily_tasks' => 'daily_tasks#create', as: 'create_daily_task'
    put '/daily_tasks' => 'daily_tasks#update', as: 'update_daily_task'
    delete '/daily_tasks/:daily_task_id' => 'daily_tasks#destroy', as: 'destroy_daily_task'

    put '/daily_task_completions/:daily_task_id' => 'daily_task_completions#update', as: 'update_daily_task_completion'
  end

  root to: 'today#show'

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/support/simulation/schedule.rb
# frozen_string_literal: true

class Support::Simulation::Schedule
  attr_reader :tasks

  def initialize
    @next_task_id = 1
    @next_daily_task_id = 1
    @tasks = []
    @used_task_indices = []
  end

  def generate_tasks
    arr = []
    rand(1..10).times do
      arr << random_task
    end

    @tasks += arr
    arr
  end

  def generate_priority_tasks(priority: 0)
    arr = []
    rand(1..5).times do
      arr << random_task(priority: priority)
    end

    @tasks += arr
    arr
  end

  def generate_daily_tasks
    arr = []
    @used_task_indices = []

    rand(1..5).times do
      i = unique_task_index
      break unless i

      current_task = @tasks[i].dup
      task_id = current_task.id
      current_task.id = next_daily_task_id
      current_task.task_id = task_id
      arr << current_task
    end

    arr
  end

  def unique_task_index
    return unless @tasks.size > @used_task_indices.size

    i = -1

    loop do
      used = false
      i = rand(0...@tasks.size)

      @used_task_indices.each do |used_i|
        if i == used_i
          used = true
          break
        end
      end

      break unless used
    end

    @used_task_indices << i
    i
  end

  def random_task(priority: rand(3))
    OpenStruct.new(
      id: next_task_id,
      name: self.class.random_task_name,
      priority: priority,
      time: self.class.random_task_duration
    )
  end

  def self.random_task_duration
    duration = "0#{rand(0..5)}:"

    minutes = rand(1..59)
    minutes = minutes < 10 ? "0#{minutes}" : minutes.to_s
    duration += minutes

    duration
  end

  def self.random_task_name
    case rand(5)
    when 3, 4
      "#{Faker::Verb.ing_form.capitalize} #{Faker::ProgrammingLanguage.name}"
    when 2
      "#{Faker::Verb.ing_form.capitalize} #{Faker::Science.element}"
    else
      Faker::Verb.ing_form.capitalize
    end
  end

  private

  def next_task_id
    id = @next_task_id
    @next_task_id += 1

    id
  end

  def next_daily_task_id
    id = @next_daily_task_id
    @next_daily_task_id += 1

    id
  end
end

app/controllers/api/schedule_controller.rb
# frozen_string_literal: true

class ::Api::ScheduleController < ::ApiController
  def show
    @priorities = []

    3.times do |i|
      @priorities << ::Task.active.where(user: current_user, priority: i).order('created_at DESC')
    end

    @daily_tasks = []
    7.times do |i|
      @daily_tasks << ::DailyTask.with_task.active.where(user: current_user, day: i).order('tasks.priority DESC, tasks.name ASC')
    end

    response = { priorities: @priorities, days: @daily_tasks.map { |el| el.as_json(with_task: true) } }

    render json: response
  end
end

app/controllers/schedule_controller.rb
# frozen_string_literal: true

class ScheduleController < ApplicationController
  before_action :set_active

  def show
    @tasks = []

    3.times do |i|
      @tasks[i] = ::Task.active.where(user: current_user, priority: i).order('created_at DESC')
    end

    @daily_tasks = []
    7.times do |i|
      @daily_tasks[i] = ::DailyTask.active.where(user: current_user, day: i)
    end
  end

  private

  def set_test_data
    simulator = ::Support::Simulation::Schedule.new
    @tasks = []
    @daily_tasks = []

    3.times do |i|
      @tasks << simulator.generate_priority_tasks(priority: i)
    end

    7.times do
      @daily_tasks << simulator.generate_daily_tasks
    end
  end

  def set_active
    @active = { schedule: 'active' }
  end
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/schedule/_create_task_modal.haml
#create-task-modal.hidden{ data: { action: 'ajax:success->schedule#taskCreated ajax:error->schedule#taskNotCreated' } }
  .modal-background{ data: { action: 'click->schedule#closeCreateTaskModal' } }
  .modal-container
    .modal.card.card-shadow.bg-light
      .modal-top
        .modal-title
          Create Task
        .modal-close-btn{ data: { action: 'click->schedule#closeCreateTaskModal' } }
          %i.fas.fa-times
      .modal-body
        = form_with(url: api_create_task_path, method: 'post', remote: true, class: 'w-full') do
          .task_name.input
            = label_tag(:name, 'Name')
            = text_field_tag(:name, nil)
          .task_priority.input
            = label_tag(:priority, 'Priority')
            = select(nil, :priority_id, Support::Priority.collection, {}, { class: 'input-mock' })
          .task_time.input
            = label_tag(:time, 'Time')
            = time_field(nil, :time, value: '00:00')
          .mb-6
          %div
            = submit_tag('Create', class: 'border-none modal-submit-btn btn bg-main bg-main-hoverable text-light')

app/views/schedule/_daily_task.haml
.card.card-hoverable.relative.bg-light{ class: "task-#{daily_task.task_id}", id: "task-per-day-#{daily_task.id}", draggable: 'true', data: { daily_task_id: daily_task.id, task_id: daily_task.task_id, action: "dragstart->schedule#dailyTaskDragStart dragend->schedule#dailyTaskDragEnd" } }
  = render 'delete_card', id: daily_task.id
  .flex.justify-between
    .left
      .name= daily_task.name
      .time-wrapper.flex.items-end.justify-between
        .mt-1
          .goal= daily_task.time
    .right.relative.mr-2.text-xl
      - priority_symbol(priority: daily_task.priority, centered: true)

app/views/schedule/_days.haml
.days-wrapper{ class: 'mt-6' }
  #left-day-arrow{ data: { action: "click->schedule#leftDay" } }
    %i.fas.fa-arrow-left
  - 7.times do |i|
    .day-of-the-week{ id: "day-#{i}" }
      .card-group.bg-group.rounded.px-4.py-4.shadow.relative{ class: 'mb-6 mt-4 mx-2 lg:mx-6', data: { day_id: i, action: "dragenter->schedule#dayDragEnter dragleave->schedule#dayDragLeave dragover->schedule#defaultDragOver drop->schedule#dayDragDrop" } }
        .card-title.day-name.text-center.text-2xl
          .day-card-plus-symbol.text-green.hidden
            - plus_symbol
          .day-card-ban-symbol.text-red.hidden
            - ban_symbol
          = t("days.#{i}")
        .cards-container
          - priority = 2
          - while priority > -1
            %div{ class: "priority-container-#{priority}" }
              - if @daily_tasks[i]
                - @daily_tasks[i].select { |dt| dt.priority == priority }.each do |dt|
                  = render 'daily_task', daily_task: dt
            - priority -= 1
  #right-day-arrow{ data: { action: "click->schedule#rightDay" } }
    %i.fas.fa-arrow-right

app/views/schedule/_delete_card.haml
.delete-card.hidden{ data: { id: id, action: "drop->schedule#deleteCardDragDrop dragover->schedule#defaultDragOver" } }
  .trash-icon.center-block
    - trash_symbol

app/views/schedule/_edit_task_modal.haml
#edit-task-modal.hidden{ data: { action: 'ajax:success->schedule#taskEdited ajax:error->schedule#taskNotEdited' } }
  .modal-background{ data: { action: 'click->schedule#closeEditTaskModal' } }
  .modal-container
    .modal.card.card-shadow.bg-light
      .modal-top
        .modal-title
          Edit Task
        .modal-close-btn{ data: { action: 'click->schedule#closeEditTaskModal' } }
          %i.fas.fa-times
      .modal-body
        = form_with(url: api_update_task_path, method: 'put', remote: true, class: 'w-full') do
          = hidden_field_tag(:id)
          .task_name.input
            = label_tag(:name, 'Name')
            = text_field_tag(:name, nil)
          .task_priority.input
            = label_tag(:priority, 'Priority')
            = select(nil, :priority_id, Support::Priority.collection, {}, { class: 'input-mock' })
          .task_time.input
            = label_tag(:time, 'Time')
            = time_field(nil, :time)
          .mb-6
          .flex.justify-between
            = submit_tag('Update', class: 'border-none w-1/2 mr-1 btn bg-main bg-main-hoverable text-light')
            .delete-btn.btn.bg-red.bg-red-hoverable.text-light{ class: 'w-1/2 ml-1', data: { action: 'click->schedule#deleteTask' } }
              Delete

app/views/schedule/_priorities.haml
.hidden
  - 3.times do |i|
    %div{ id: "priority-example-#{i}" }
      - priority_symbol(priority: i, centered: true)

.task-priority-wrapper
  #left-priority-arrow{ data: { action: "click->schedule#leftPriority" } }
    %i.fas.fa-arrow-left
  - 3.times do |i|
    .priority-card{ id: "priority-#{i}" }
      .card-group.bg-light-main.rounded.px-4.py-4.mt-4.shadow.mb-6.relative{ class: 'lg:mx-6' }
        .card-title.flex.justify-between{ class: "text-priority-#{i}" }
          %div
            - priority_symbol(priority: i)
            = t("priorities.#{i}")
          .btn.add-btn.bg-main-hoverable.text-light.shadow{ id: "add-#{i}", data: { action: 'click->schedule#openCreateTaskModal', priority: i } }
            %i.fas.fa-plus
        .card-body
          - @tasks[i].each do |t|
            = render 'task', task: t
  #right-priority-arrow{ data: { action: "click->schedule#rightPriority" } }
    %i.fas.fa-arrow-right

app/views/schedule/_task.haml
.card.card-hoverable.relative.bg-light{ class: "task-#{task.id}", id: "task-#{task.id}", draggable: 'true', data: { task_id: task.id, priority: task.priority, action: "click->schedule#openEditTaskModal dragstart->schedule#taskDragStart dragend->schedule#taskDragEnd" } }
  .flex.justify-between
    .left
      .name= task.name
      .time-wrapper.flex.items-end.justify-between
        .mt-1
          .goal= task.time
    .right.relative.mr-2.text-xl
      - priority_symbol(priority: task.priority, centered: true)

app/views/schedule/show.haml
-# Sounds have been taken from http://www.orangefreesounds.com/
= content_for :title, 'Schedule | Daily Manager'
= render 'shared/nav'

%main.px-5{ data: { controller: 'schedule' } }
  = render 'shared/alerts'
  .hidden
    #add-card-container
      .card.add-card.relative.bg-light.hidden
        .text-center.center-block
          - plus_symbol
    #delete-card-container
      = render 'delete_card', id: 1
    #new-task-container
      = render 'task', task: OpenStruct.new
  .text-lg.mb-4.lg:mb-10.lg:text-2xl
    .black-bottom.mx-auto.w-32.text-center.lg:w-64
      Schedule
  = render 'priorities'
  = render 'days'
  = render 'create_task_modal'
  = render 'edit_task_modal'